### ISSUE TITLE
Can't download the pretrained model

### ISSUE THREAD

**Issue by wyl2077** [zlzeng/DeepBulidingPlanes#2]
The downkoad link cannot access，please updata it. Thanks so much.

**Comment by zlzeng** [comment]
Hi,

Try this link: pretrained
<https://mycuhk-my.sharepoint.com/:f:/g/personal/1155052510_link_cuhk_edu_hk/EtLG7-_nxnNOsfTLzyKyyd8BpwJ7AJ8XmONu46Hwi3gTYA?e=f35wEa>

Best,
ZENG Zhiliang

**Comment by wyl2077** [comment]
Thanks, it works.
